# Base image
FROM python:3.9-slim

# Set environment variables
ENV FLASK_APP=core/server.py
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . .

# Expose the port the app will run on
EXPOSE 8000

# Run database migrations and then start the application
CMD ["bash", "run.sh"]
